# Generated by Django 3.2.9 on 2021-12-05 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('event_date_time', models.DateTimeField()),
                ('price_1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pool_1', models.IntegerField()),
                ('pool_date_1', models.DateTimeField()),
                ('price_2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pool_2', models.IntegerField()),
                ('pool_date_2', models.DateTimeField()),
                ('price_3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pool_3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_sold', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('promotor', models.CharField(blank=True, max_length=4)),
                ('bought_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='website.event')),
            ],
        ),
    ]
