# Generated by Django 3.2.9 on 2022-02-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_event_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='active',
            new_name='visible',
        ),
    ]
