# Generated by Django 3.2.9 on 2022-02-05 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=50)),
                ('voivodeship', models.CharField(choices=[(1, 'Dolnośląskie'), (2, 'Kujawsko-pomorskie'), (3, 'Lubelskie'), (4, 'Lubuskie'), (5, 'Łódzkie'), (6, 'Małopolskie'), (7, 'Mazowieckie'), (8, 'Opolskie'), (9, 'Podkarpackie'), (10, 'Podlaskie'), (11, 'Pomorskie'), (12, 'Śląskie'), (13, 'Świętokrzyskie'), (14, 'Warmińsko-mazurskie'), (15, 'Wielkopolskie'), (16, 'Zachodniopomorskie')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.city')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('instagram', models.CharField(blank=True, max_length=255)),
                ('linkedin', models.CharField(blank=True, max_length=255)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.club')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.club'),
        ),
    ]
