# Generated by Django 3.2.9 on 2022-02-11 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20220211_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='promotor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.promotor'),
        ),
    ]
