# Generated by Django 3.2.9 on 2022-02-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_ticket_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='id',
            new_name='ticket_id',
        ),
    ]
