# Generated by Django 3.2.9 on 2022-02-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_rename_id_ticket_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_promotor',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
