# Generated by Django 3.2.9 on 2022-02-17 16:17

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20220217_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['city']),
        ),
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name', 'event_date_time']),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['ticket_id']),
        ),
    ]
