# Generated by Django 3.2.9 on 2022-03-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_ticket_pool_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pool_number',
            field=models.IntegerField(),
        ),
    ]
